# Generated by Django 3.0.3 on 2020-05-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airport_fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='airport_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.TextField()),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='airports_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('website_link', models.TextField()),
                ('weather_href', models.TextField()),
                ('weather_pics_link', models.TextField()),
            ],
        ),
    ]
