# Generated by Django 3.0.3 on 2020-05-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport_fact',
            name='city',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
